export const DEFAULT_CONTENT: Record<string, string> = {
  // === Navbar ===
  'nav-brand': 'Vios Growth Academy',
  'nav-link-1': 'The Vision',
  'nav-link-2': 'Founder',
  'nav-link-3': 'Impact',
  'nav-link-4': 'Success Stories',
  'nav-link-5': 'Pillars',
  'nav-our-story': 'Our Story',
  'nav-partner': 'Partner',
  'nav-contact': 'Contact',
  'nav-support': 'Support',

  // === Hero ===
  'hero-subtitle': 'Restorative Elegance',
  'hero-title-line1': 'The Growth of',
  'hero-title-line2': 'Human Lives',
  'hero-title-accent': 'Growth',
  'hero-description': "Transforming the cracks of rejection into the gold of dignity. We believe every broken story holds the potential for a masterpiece.",
  'hero-btn-support': 'Support the Redirection',
  'hero-btn-story': 'Our Story',
  'hero-stat-1-label': 'Lives Restored',
  'hero-stat-1-value': '100+',
  'hero-stat-2-label': 'Years of Impact',
  'hero-stat-2-value': '1',
  'hero-stat-3-label': 'Transparency',
  'hero-stat-3-value': '100%',
  'hero-image-1': './WhatsApp Image 2026-03-23 at 23.35.49.jpeg',
  'hero-image-2': './WhatsApp Image 2026-06-01 at 17.17.04 (2).jpeg',
  'hero-image-3': './WhatsApp Image 2026-03-23 at 23.44.12.jpeg',

  // === Golden Hour / Gallery ===
  'gallery-subtitle': 'The Golden Hour',
  'gallery-title': 'Moments of Restoration',
  'gallery-description': 'Explore scenes of healing and community growth from Vios Growth Academy. Drag or scroll to browse the gallery.',

  // === Founder ===
  'founder-section-label': 'Founder and Leader',
  'founder-name': 'Nakungu Violet Lovisa',
  'founder-image': './Coach-vio2.jpeg',
  'founder-para-1': 'Her life began with rejection, pain, and feeling unseen as a child. But, instead of letting that pain break her, she chose to transform it into purpose.',
  'founder-para-2': 'Through music, mentorship, and community work, she discovered her calling to bring hope to children, women and communities who feel unforgotten.',
  'founder-para-3': 'She leads Vios Growth Academy, a growing community initiative focused on financial guidance, personal development, emotional intelligence, and supporting vulnerable children.',
  'founder-identity-1-title': 'DJ Vio',
  'founder-identity-1-subtitle': 'The Vibe Mama',
  'founder-identity-1-desc': 'A melody lady taking over the decks, using the universal language of rhythm to bridge the gap between the unheard and the world.',
  'founder-identity-2-title': 'Rasta Vio',
  'founder-identity-2-subtitle': 'Identity',
  'founder-identity-2-desc': 'Finding strength in roots and the courage to stand firm in one\'s true essence despite childhood rejection and pain.',
  'founder-identity-3-title': 'Coach Vio',
  'founder-identity-3-subtitle': 'The Vibe Master',
  'founder-identity-3-desc': 'Guiding the next generation to transform their scars into stars of leadership through emotional intelligence and mentorship.',
  'founder-quote': '"My pain became someone else\'s hope. Every crack in my story was just a place for the gold to settle."',

  // === Course Section ===
  'course-subtitle': 'Psychological & Educational Course',
  'course-title-line1': 'Transforming Rejection',
  'course-title-line2': 'into Resilience',
  'course-title-accent': 'into Resilience',
  'course-description': 'Our "Black Sheep" curriculum is a specialized psychological framework designed for those who have felt marginalized or rejected. We provide the tools to heal generational wounds and step into a legacy of dignity.',
  'course-form-title': 'Request a Free 30-Min Consultation',
  'course-btn-text': 'Claim My Free Consultation',
  'course-image': './BlackSheep_course.png',
  'course-image-badge': 'Educational Excellence',
  'course-image-title': 'The Black Sheep Course',
  'course-image-desc': 'A psychological journey to reclaiming your worth.',
  'course-success-msg': 'Thank you for taking this step. We\'ve received your request and will reach out to schedule your consultation within 24 hours.',

  // === Impact ===
  'impact-section-label': "The 'Angels' Impact",
  'impact-section-title': 'Restoring Dignity',
  'impact-card-1-title': 'Abandoned & Homeless',
  'impact-card-1-desc': 'Providing immediate shelter and a sense of belonging to those left behind by society.',
  'impact-card-1-detailed': 'Our street outreach programs identify vulnerable individuals and provide them with immediate safe housing, nutritious meals, and the psychological support needed to begin the journey of restoration.',
  'impact-card-1-image': './Restoring_Dignity1.jpeg',
  'impact-card-2-title': 'Rejected by Systems',
  'impact-card-2-desc': 'Legal advocacy and structural support for those marginalized by bureaucratic indifference.',
  'impact-card-2-detailed': 'We bridge the gap between marginalized communities and the systems meant to serve them, providing legal aid and documentation support to ensure every individual is seen and protected by the law.',
  'impact-card-2-image': './Rejectbysystems2.jpg',
  'impact-card-3-title': 'Unable to School',
  'impact-card-3-desc': 'Restoring the right to education through scholarships and vocational training programs.',
  'impact-card-3-detailed': 'Education is the ultimate tool for independence. We provide full scholarships, school supplies, and vocational training to ensure that financial barriers never stand in the way of a child\'s potential.',
  'impact-card-3-image': './Restoring_Dignity3.jpeg',
  'impact-approach-title': 'Our Approach',
  'impact-approach-1': 'Immediate intervention and safety assessment',
  'impact-approach-2': 'Long-term structural support and advocacy',
  'impact-approach-3': 'Community reintegration and empowerment',

  // === Stories ===
  'stories-section-label': 'Success Stories',
  'stories-section-title': 'Restored Masterpieces',
  'stories-section-desc': 'Witness the transformation of lives that were once considered broken, now shining with the gold of dignity.',
  'stories-card-1-title': 'From Street to Scholar',
  'stories-card-1-subtitle': 'The Story of David',
  'stories-card-1-desc': 'Once homeless, David is now pursuing a degree in Social Work to give back to his community.',
  'stories-card-1-full': 'David\'s journey began on the cold pavement of the city center. For three years, he was a shadow in the crowd, overlooked and forgotten. When he first arrived at Vios, he was skeptical of the "dignity" we promised. But through our Kintsugi approach, he began to see his past not as a source of shame, but as a unique strength. Today, David is a top student at the university, using his lived experience to advocate for those still on the streets. He is living proof that a broken vessel, once restored, can hold more beauty than it ever did before.',
  'stories-card-1-image': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=75&w=1000',
  'stories-card-1-video': '',
  'stories-card-2-title': 'Breaking the Silence',
  'stories-card-2-subtitle': 'The Story of Sarah',
  'stories-card-2-desc': 'Sarah overcame systemic abuse to become a leading legal advocate for women\'s rights in her region.',
  'stories-card-2-full': 'Sarah spent years in a silence imposed by fear. Systemic abuse had stripped her of her voice and her agency. At Vios, she found a community that didn\'t just listen, but empowered her to speak. She transitioned from a survivor to a warrior. After completing our legal literacy program, she pursued a law degree. Sarah now leads a non-profit that provides legal aid to women facing similar struggles. Her voice, once silenced, now echoes in courtrooms, demanding justice and restoring the dignity of countless others.',
  'stories-card-2-image': 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=75&w=1000',
  'stories-card-2-video': '',
  'stories-card-3-title': "The Entrepreneur's Spark",
  'stories-card-3-subtitle': 'The Story of Michael',
  'stories-card-3-desc': 'With a micro-loan and mentorship, Michael built a sustainable furniture business that employs 10 people.',
  'stories-card-3-full': 'Michael had the skill but lacked the opportunity. A talented carpenter, he was stuck in a cycle of day labor that barely paid for his next meal. Vios saw the "spark" in his craftsmanship. Through our micro-entrepreneurship program, he received a small loan and business mentorship. He didn\'t just build a business; he built a legacy. Michael\'s Furniture now exports pieces that celebrate traditional techniques. More importantly, he employs ten young men from our vocational program, passing on the dignity of work to the next generation.',
  'stories-card-3-image': 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=75&w=1000',
  'stories-card-3-video': '',
  'stories-card-4-title': 'A Home Restored',
  'stories-card-4-subtitle': 'The Story of Grace',
  'stories-card-4-desc': 'Grace found a family and a future at Vios, transforming her childhood trauma into a passion for teaching.',
  'stories-card-4-full': 'Grace\'s early years were marked by instability and loss. She moved between foster homes, never finding a place to call her own. When she came to the Vios Children Foundation, she finally found her "forever family". The stability and love she received allowed her to heal from her childhood trauma. Grace discovered a natural talent for teaching and a deep empathy for children facing similar hardships. She is now a lead teacher at our Academy, providing the same foundation of love and dignity that saved her life.',
  'stories-card-4-image': 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=75&w=1000',
  'stories-card-4-video': '',

  // === Pillars ===
  'pillars-section-label': 'Sectors of Impact',
  'pillars-section-title': 'The Restorative Pillars',
  'pillars-section-desc': 'Our holistic approach addresses the root causes of rejection, providing the tools for long-term, sustainable dignity across four core sectors.',
  'pillar-1-title': 'Vios Children Foundation',
  'pillar-1-subtitle': 'Nurturing Future Leaders',
  'pillar-1-desc': 'A safe haven where childhood is protected and potential is nurtured through holistic education and emotional support. We bring hope to children and communities who feel unforgotten.',
  'pillar-1-detailed': 'The Vios Children Foundation is dedicated to providing a safe, nurturing environment for children who have been abandoned, orphaned, or left behind by society. We believe that every child deserves a childhood filled with love, learning, and the opportunity to grow into a visionary leader.',
  'pillar-2-title': 'Empowering Men and Boys',
  'pillar-2-subtitle': 'Empowering Wednesdays',
  'pillar-2-desc': 'Cultivating male leadership and emotional intelligence to break cycles of toxic masculinity. We empower men and boys to become empathetic, responsible pillars of their families and society.',
  'pillar-2-detailed': 'Our Empowering Wednesdays program focuses on cultivating male leadership and emotional intelligence. By breaking cycles of toxic masculinity, we empower men and boys to become empathetic, responsible pillars of their families and society through mentorship and community building.',
  'pillar-3-title': 'Fearless Women of Worth',
  'pillar-3-subtitle': 'Fearless Fridays',
  'pillar-3-desc': 'Providing vocational training and legal literacy to empower women to claim their future. We equip women with the tools to protect their rights and lead with unwavering confidence.',
  'pillar-3-detailed': 'Through Fearless Fridays, we provide vocational training and legal literacy to empower women to claim their future. We equip women with the tools to protect their rights, achieve financial independence, and lead their communities with unwavering confidence.',
  'pillar-4-title': 'Financial Guidance',
  'pillar-4-subtitle': 'Financial Mondays',
  'pillar-4-desc': 'Transforming the mindset from dependency to dignity through sustainable growth. Our programs provide the mentorship needed to build self-sustaining legacies and financial independence.',
  'pillar-4-detailed': 'Our Financial Mondays program transforms the mindset from dependency to dignity through sustainable growth. We provide the mentorship and micro-entrepreneurship training needed to build self-sustaining legacies and achieve long-term financial independence.',

  // === Transparency ===
  'transparency-section-label': 'Radical Transparency',
  'transparency-section-title': 'The Living Archive',
  'transparency-section-desc': 'We believe that trust is the gold that binds our community. Our "Certified Ethical Financial Management" ensures that every investment goes directly to restoring lives.',
  'transparency-stat-1-label': 'Transparency Score',
  'transparency-stat-1-value': '100%',
  'transparency-stat-2-label': 'Direct Impact',
  'transparency-stat-2-value': '92%',
  'transparency-stat-3-label': 'Lives Restored',
  'transparency-stat-3-value': '100+',
  'transparency-stat-4-label': 'Certified Years',
  'transparency-stat-4-value': '1',

  // === FAQ ===
  'faq-section-label': 'Common Questions',
  'faq-section-title': 'Frequently Asked Questions',
  'faq-q-1': 'What is the core mission of Vios Growth Academy?',
  'faq-a-1': 'Our mission is to transform rejection into rhythm and heartbreak into healing. We provide a sanctuary and a growth engine for those marginalized by society, focusing on restoring dignity through education, advocacy, and sustainable financial guidance.',
  'faq-q-2': 'How can I support the Academy\'s programs?',
  'faq-a-2': 'You can support us by making a direct donation, becoming a strategic partner, or joining our mentorship circle. Every contribution goes toward our core pillars, including child protection, legal advocacy, and economic empowerment.',
  'faq-q-3': 'Where does my donation go?',
  'faq-a-3': 'We practice Radical Transparency. 92% of your donation goes directly to our impact programs. We provide regular financial audits and impact reports to show exactly how your investment is restoring lives.',
  'faq-q-4': 'What are the four core pillars of the Academy?',
  'faq-a-4': 'Our work is built on four sectors: Vios Children Foundation (protection & education), Empowering Men and Boys (leadership & emotional intelligence), Fearless Women of Worth (agency & vocational training), and Financial Guidance (ending aid dependency).',
  'faq-q-5': 'How do I become a mentor?',
  'faq-a-5': 'If you are an industry leader or professional looking to share your expertise, you can apply through our Partner With Us page. Our Mentorship Circle connects leaders with our students to provide high-level guidance for sustainable growth.',

  // === Social Feed Section ===
  'social-section-label': 'Stay Connected',
  'social-section-title': 'Follow the Journey',
  'social-section-desc': 'Join our community on social media to see real-time updates, success stories, and the daily impact of Vios Growth Academy.',

  // === Our Story Page ===
  'story-hero-image': './OurStory.jpg',
  'story-hero-title': 'Founded in 2025',
  'story-quote': '"I am no longer seeking acceptance; I am becoming everything I was created to be. I rose above it all—not by revenge, but by love."',
  'story-quote-author': '— Coach Vio',
  'story-section-1-title': 'The Story That Built an Academy',
  'story-section-1-para-1': 'Every great movement begins with a spark. For Vios Growth Academy, that spark is the harrowing yet triumphant journey of our founder, Nakungu Violet Lovisa (Coach Vio).',
  'story-section-1-para-2': 'Her life began with rejection, pain, and feeling unseen. But instead of letting that pain break her, she chose to transform it into purpose. Through music, mentorship, and community work, she discovered her calling to bring hope to those who feel unforgotten.',
  'story-section-1-para-3': 'Coach Vio\'s resilience is the bedrock of our philosophy. She didn\'t just survive; she thrived, turning the cracks of her own story into a masterpiece of service.',
  'story-section-2-title': 'The Black Sheep Daughter',
  'story-section-2-para-1': '"The Black Sheep Daughter: My Truth Unveiled" is more than just a book; it is a blueprint for transforming rejection into rhythm and heartbreak into healing. From being a child who felt "unwanted" to becoming a global voice for empowerment, Coach Vio\'s story is the ultimate testimony to the human spirit.',
  'story-section-2-para-2': 'This narrative serves as the foundational curriculum for our academy, teaching our students that their history does not define their destiny.',
  'story-section-3-title': 'Our Evolution',
  'story-section-3-para-1': 'What started as a small initiative to provide shelter to the homeless has evolved into a multi-sector academy. Today, we operate across four core pillars: protecting children, empowering men and boys, uplifting women, and providing the financial guidance necessary for sustainable independence.',
  'story-section-3-para-2': 'We are not just a charity; we are a growth engine. We believe in radical transparency, ethical management, and the unwavering belief that every individual has the right to a legacy of dignity.',
  'story-sidebar-years-label': 'Years of Impact',
  'story-sidebar-years-value': '1+',
  'story-sidebar-lives-label': 'Lives Restored',
  'story-sidebar-lives-value': '100+',
  'story-sidebar-pillars-label': 'Core Pillars',
  'story-sidebar-pillars-value': '4',
  'story-sidebar-quote': '"We don\'t just fix what\'s broken; we make it stronger than it was before."',
  'story-btn-back': 'Back to Academy',

  // === Partner Page ===
  'partner-section-label': 'Strategic Alliances',
  'partner-title': 'Partner with the Academy',
  'partner-quote': '"We don\'t just seek donors; we seek visionaries who understand that restoring dignity is the most sustainable investment one can make."',
  'partner-hero-image': './Partnerimage.jpeg',
  'partner-hero-title': 'Building Legacies Together',
  'partner-tier-1-title': 'Corporate CSR',
  'partner-tier-1-desc': 'Align your brand with radical transparency and measurable social impact. We offer tailored CSR programs that resonate with your corporate values.',
  'partner-tier-2-title': 'Strategic Grants',
  'partner-tier-2-desc': 'For foundations and philanthropic organizations looking to fund structural change in the sectors of education, legal advocacy, and economic empowerment.',
  'partner-tier-3-title': 'Mentorship Circle',
  'partner-tier-3-desc': 'Share your expertise. We connect industry leaders with our students to provide the high-level guidance needed for sustainable professional growth.',
  'partner-cta-title': 'Ready to start the journey?',
  'partner-cta-desc': 'Our partnership team is ready to discuss how we can co-create a legacy of dignity and growth.',
  'partner-cta-btn': 'INQUIRE ABOUT PARTNERSHIP',

  // === Contact Page ===
  'contact-section-label': 'Contact the Sanctuary',
  'contact-title': 'Every story starts with a conversation.',
  'contact-title-accent': 'conversation.',
  'contact-desc': 'We believe in radical availability. Whether you\'re seeking a safe haven, looking to invest in a vision, or simply want to learn more about our heartbeat, we are here to listen.',
  'contact-group-1-title': 'Electronic Mail',
  'contact-group-1-label': 'General Inquiries',
  'contact-group-1-value': 'vio@viosgrowthacademy.com',
  'contact-group-2-title': 'Voice Communication',
  'contact-group-2-label': 'Academy Office',
  'contact-group-2-value': '+256 705 154 403',
  'contact-form-title': 'Send a Direct Message',
  'contact-form-desc': 'Have a specific inquiry? Our team usually responds immediately. Your message is kept in strict confidence.',
  'contact-btn-text': 'SEND MESSAGE',

  // === Footer ===
  'footer-title-line1': 'Will you be the',
  'footer-title-accent': 'gold',
  'footer-title-line2': 'in the cracks?',
  'footer-quote': '"I am no longer seeking acceptance; I am becoming everything I was created to be. I rose above it all—not by revenge, but by love."',
  'footer-quote-author': '— Coach Vio',
  'footer-btn-invest': 'Invest / Donate',
  'footer-btn-partner': 'Partner With Us',
  'footer-form-title': 'Direct Inquiry',
  'footer-form-btn': 'Send Message',
  'footer-form-success': 'Message Received!',
  'footer-nav-title': 'Navigation',
  'footer-nav-vision': 'Our Vision',
  'footer-nav-reports': 'Impact Reports',
  'footer-nav-academy': 'The Academy',
  'footer-nav-faq': 'FAQs',
  'footer-nav-contact': 'Contact Us',
  'footer-connect-title': 'Connect',
  'footer-copyright': '© 2026 Vios Growth Academy. All Rights Reserved.',
  'footer-email': 'viosgrowthacademy@gmail.com',
  'footer-brand': 'Vios Growth Academy',

  // === Donation Modal ===
  'donation-title': 'Invest in Dignity',
  'donation-success-title': 'Investment Confirmed',
  'donation-desc': 'Your investment directly funds the restoration of lives. Choose an amount to contribute to our mission.',
  'donation-amount-label': 'Contribution Amount',
  'donation-btn-confirm': 'Contribution',
  'donation-processing': 'Processing Investment...',
  'donation-return': 'Return to Academy',
  'donation-success-msg': 'Your contribution has been received. Thank you for helping us restore dignity and growth.',

  // === Search Modal ===
  'search-placeholder': 'Search programs, stories, impact...',
  'search-empty': 'Type something or select a category to explore...',
  'search-no-results': 'No results found for your selection',

  // === Partnership Modal ===
  'partner-inquiry-title': 'Strategic Alliance Inquiry',
  'partner-inquiry-success-title': 'Inquiry Received',
  'partner-inquiry-desc': 'We co-create deep, sustainable impact through corporate CSR, strategic grants, and cooperative mentorship. Please outline your proposal below.',
  'partner-inquiry-success': 'Your strategic partnership request has been securely logged. Our alliances team will review your proposal and get in touch within 2 business days.',
};

export const CONTENT_SECTIONS: Record<string, { key: string; label: string; type: 'text' | 'image' | 'video' }[]> = {
  'Navigation': [
    { key: 'nav-brand', label: 'Brand Name', type: 'text' },
    { key: 'nav-link-1', label: 'Nav Link 1', type: 'text' },
    { key: 'nav-link-2', label: 'Nav Link 2', type: 'text' },
    { key: 'nav-link-3', label: 'Nav Link 3', type: 'text' },
    { key: 'nav-link-4', label: 'Nav Link 4', type: 'text' },
    { key: 'nav-link-5', label: 'Nav Link 5', type: 'text' },
    { key: 'nav-our-story', label: 'Our Story Link', type: 'text' },
    { key: 'nav-partner', label: 'Partner Link', type: 'text' },
    { key: 'nav-contact', label: 'Contact Link', type: 'text' },
    { key: 'nav-support', label: 'Support Button', type: 'text' },
  ],
  'Hero': [
    { key: 'hero-subtitle', label: 'Subtitle', type: 'text' },
    { key: 'hero-title-line1', label: 'Title Line 1', type: 'text' },
    { key: 'hero-title-line2', label: 'Title Line 2', type: 'text' },
    { key: 'hero-title-accent', label: 'Title Accent Word', type: 'text' },
    { key: 'hero-description', label: 'Description', type: 'text' },
    { key: 'hero-btn-support', label: 'Support Button', type: 'text' },
    { key: 'hero-btn-story', label: 'Story Button', type: 'text' },
    { key: 'hero-stat-1-label', label: 'Stat 1 Label', type: 'text' },
    { key: 'hero-stat-1-value', label: 'Stat 1 Value', type: 'text' },
    { key: 'hero-stat-2-label', label: 'Stat 2 Label', type: 'text' },
    { key: 'hero-stat-2-value', label: 'Stat 2 Value', type: 'text' },
    { key: 'hero-stat-3-label', label: 'Stat 3 Label', type: 'text' },
    { key: 'hero-stat-3-value', label: 'Stat 3 Value', type: 'text' },
    { key: 'hero-image-1', label: 'Hero Image 1', type: 'image' },
    { key: 'hero-image-2', label: 'Hero Image 2', type: 'image' },
    { key: 'hero-image-3', label: 'Hero Image 3', type: 'image' },
  ],
  'Founder': [
    { key: 'founder-section-label', label: 'Section Label', type: 'text' },
    { key: 'founder-name', label: 'Founder Name', type: 'text' },
    { key: 'founder-image', label: 'Founder Image', type: 'image' },
    { key: 'founder-para-1', label: 'Paragraph 1', type: 'text' },
    { key: 'founder-para-2', label: 'Paragraph 2', type: 'text' },
    { key: 'founder-para-3', label: 'Paragraph 3', type: 'text' },
    { key: 'founder-identity-1-title', label: 'Identity 1 Title', type: 'text' },
    { key: 'founder-identity-1-subtitle', label: 'Identity 1 Subtitle', type: 'text' },
    { key: 'founder-identity-1-desc', label: 'Identity 1 Description', type: 'text' },
    { key: 'founder-identity-2-title', label: 'Identity 2 Title', type: 'text' },
    { key: 'founder-identity-2-subtitle', label: 'Identity 2 Subtitle', type: 'text' },
    { key: 'founder-identity-2-desc', label: 'Identity 2 Description', type: 'text' },
    { key: 'founder-identity-3-title', label: 'Identity 3 Title', type: 'text' },
    { key: 'founder-identity-3-subtitle', label: 'Identity 3 Subtitle', type: 'text' },
    { key: 'founder-identity-3-desc', label: 'Identity 3 Description', type: 'text' },
    { key: 'founder-quote', label: 'Quote', type: 'text' },
  ],
  'Course Section': [
    { key: 'course-subtitle', label: 'Section Subtitle', type: 'text' },
    { key: 'course-title-line1', label: 'Title Line 1', type: 'text' },
    { key: 'course-title-line2', label: 'Title Line 2', type: 'text' },
    { key: 'course-title-accent', label: 'Title Accent', type: 'text' },
    { key: 'course-description', label: 'Description', type: 'text' },
    { key: 'course-form-title', label: 'Form Title', type: 'text' },
    { key: 'course-btn-text', label: 'Button Text', type: 'text' },
    { key: 'course-image', label: 'Course Image', type: 'image' },
    { key: 'course-image-badge', label: 'Image Badge', type: 'text' },
    { key: 'course-image-title', label: 'Image Title', type: 'text' },
    { key: 'course-image-desc', label: 'Image Description', type: 'text' },
  ],
  'Impact': [
    { key: 'impact-section-label', label: 'Section Label', type: 'text' },
    { key: 'impact-section-title', label: 'Section Title', type: 'text' },
    { key: 'impact-card-1-title', label: 'Card 1 Title', type: 'text' },
    { key: 'impact-card-1-desc', label: 'Card 1 Description', type: 'text' },
    { key: 'impact-card-1-detailed', label: 'Card 1 Detailed', type: 'text' },
    { key: 'impact-card-1-image', label: 'Card 1 Image', type: 'image' },
    { key: 'impact-card-2-title', label: 'Card 2 Title', type: 'text' },
    { key: 'impact-card-2-desc', label: 'Card 2 Description', type: 'text' },
    { key: 'impact-card-2-detailed', label: 'Card 2 Detailed', type: 'text' },
    { key: 'impact-card-2-image', label: 'Card 2 Image', type: 'image' },
    { key: 'impact-card-3-title', label: 'Card 3 Title', type: 'text' },
    { key: 'impact-card-3-desc', label: 'Card 3 Description', type: 'text' },
    { key: 'impact-card-3-detailed', label: 'Card 3 Detailed', type: 'text' },
    { key: 'impact-card-3-image', label: 'Card 3 Image', type: 'image' },
  ],
  'Success Stories': [
    { key: 'stories-section-label', label: 'Section Label', type: 'text' },
    { key: 'stories-section-title', label: 'Section Title', type: 'text' },
    { key: 'stories-section-desc', label: 'Section Description', type: 'text' },
    { key: 'stories-card-1-title', label: 'Story 1 Title', type: 'text' },
    { key: 'stories-card-1-subtitle', label: 'Story 1 Subtitle', type: 'text' },
    { key: 'stories-card-1-desc', label: 'Story 1 Short Description', type: 'text' },
    { key: 'stories-card-1-full', label: 'Story 1 Full Story', type: 'text' },
    { key: 'stories-card-1-image', label: 'Story 1 Image', type: 'image' },
    { key: 'stories-card-1-video', label: 'Story 1 Video', type: 'video' },
    { key: 'stories-card-2-title', label: 'Story 2 Title', type: 'text' },
    { key: 'stories-card-2-subtitle', label: 'Story 2 Subtitle', type: 'text' },
    { key: 'stories-card-2-desc', label: 'Story 2 Short Description', type: 'text' },
    { key: 'stories-card-2-full', label: 'Story 2 Full Story', type: 'text' },
    { key: 'stories-card-2-image', label: 'Story 2 Image', type: 'image' },
    { key: 'stories-card-2-video', label: 'Story 2 Video', type: 'video' },
    { key: 'stories-card-3-title', label: 'Story 3 Title', type: 'text' },
    { key: 'stories-card-3-subtitle', label: 'Story 3 Subtitle', type: 'text' },
    { key: 'stories-card-3-desc', label: 'Story 3 Short Description', type: 'text' },
    { key: 'stories-card-3-full', label: 'Story 3 Full Story', type: 'text' },
    { key: 'stories-card-3-image', label: 'Story 3 Image', type: 'image' },
    { key: 'stories-card-3-video', label: 'Story 3 Video', type: 'video' },
    { key: 'stories-card-4-title', label: 'Story 4 Title', type: 'text' },
    { key: 'stories-card-4-subtitle', label: 'Story 4 Subtitle', type: 'text' },
    { key: 'stories-card-4-desc', label: 'Story 4 Short Description', type: 'text' },
    { key: 'stories-card-4-full', label: 'Story 4 Full Story', type: 'text' },
    { key: 'stories-card-4-image', label: 'Story 4 Image', type: 'image' },
    { key: 'stories-card-4-video', label: 'Story 4 Video', type: 'video' },
  ],
  'Pillars': [
    { key: 'pillars-section-label', label: 'Section Label', type: 'text' },
    { key: 'pillars-section-title', label: 'Section Title', type: 'text' },
    { key: 'pillars-section-desc', label: 'Section Description', type: 'text' },
    { key: 'pillar-1-title', label: 'Pillar 1 Title', type: 'text' },
    { key: 'pillar-1-subtitle', label: 'Pillar 1 Subtitle', type: 'text' },
    { key: 'pillar-1-desc', label: 'Pillar 1 Description', type: 'text' },
    { key: 'pillar-1-detailed', label: 'Pillar 1 Detailed', type: 'text' },
    { key: 'pillar-2-title', label: 'Pillar 2 Title', type: 'text' },
    { key: 'pillar-2-subtitle', label: 'Pillar 2 Subtitle', type: 'text' },
    { key: 'pillar-2-desc', label: 'Pillar 2 Description', type: 'text' },
    { key: 'pillar-2-detailed', label: 'Pillar 2 Detailed', type: 'text' },
    { key: 'pillar-3-title', label: 'Pillar 3 Title', type: 'text' },
    { key: 'pillar-3-subtitle', label: 'Pillar 3 Subtitle', type: 'text' },
    { key: 'pillar-3-desc', label: 'Pillar 3 Description', type: 'text' },
    { key: 'pillar-3-detailed', label: 'Pillar 3 Detailed', type: 'text' },
    { key: 'pillar-4-title', label: 'Pillar 4 Title', type: 'text' },
    { key: 'pillar-4-subtitle', label: 'Pillar 4 Subtitle', type: 'text' },
    { key: 'pillar-4-desc', label: 'Pillar 4 Description', type: 'text' },
    { key: 'pillar-4-detailed', label: 'Pillar 4 Detailed', type: 'text' },
  ],
  'Transparency': [
    { key: 'transparency-section-label', label: 'Section Label', type: 'text' },
    { key: 'transparency-section-title', label: 'Section Title', type: 'text' },
    { key: 'transparency-section-desc', label: 'Section Description', type: 'text' },
    { key: 'transparency-stat-1-label', label: 'Stat 1 Label', type: 'text' },
    { key: 'transparency-stat-1-value', label: 'Stat 1 Value', type: 'text' },
    { key: 'transparency-stat-2-label', label: 'Stat 2 Label', type: 'text' },
    { key: 'transparency-stat-2-value', label: 'Stat 2 Value', type: 'text' },
    { key: 'transparency-stat-3-label', label: 'Stat 3 Label', type: 'text' },
    { key: 'transparency-stat-3-value', label: 'Stat 3 Value', type: 'text' },
    { key: 'transparency-stat-4-label', label: 'Stat 4 Label', type: 'text' },
    { key: 'transparency-stat-4-value', label: 'Stat 4 Value', type: 'text' },
  ],
  'FAQ': [
    { key: 'faq-section-label', label: 'Section Label', type: 'text' },
    { key: 'faq-section-title', label: 'Section Title', type: 'text' },
  ],
  'Our Story Page': [
    { key: 'story-hero-image', label: 'Hero Image', type: 'image' },
    { key: 'story-hero-title', label: 'Hero Title', type: 'text' },
    { key: 'story-quote', label: 'Quote', type: 'text' },
    { key: 'story-quote-author', label: 'Quote Author', type: 'text' },
    { key: 'story-section-1-title', label: 'Section 1 Title', type: 'text' },
    { key: 'story-section-2-title', label: 'Section 2 Title', type: 'text' },
    { key: 'story-section-3-title', label: 'Section 3 Title', type: 'text' },
    { key: 'story-sidebar-years-label', label: 'Sidebar Years Label', type: 'text' },
    { key: 'story-sidebar-years-value', label: 'Sidebar Years Value', type: 'text' },
    { key: 'story-sidebar-lives-label', label: 'Sidebar Lives Label', type: 'text' },
    { key: 'story-sidebar-lives-value', label: 'Sidebar Lives Value', type: 'text' },
    { key: 'story-sidebar-pillars-label', label: 'Sidebar Pillars Label', type: 'text' },
    { key: 'story-sidebar-pillars-value', label: 'Sidebar Pillars Value', type: 'text' },
    { key: 'story-sidebar-quote', label: 'Sidebar Quote', type: 'text' },
    { key: 'story-btn-back', label: 'Back Button', type: 'text' },
  ],
  'Partner Page': [
    { key: 'partner-section-label', label: 'Section Label', type: 'text' },
    { key: 'partner-title', label: 'Page Title', type: 'text' },
    { key: 'partner-quote', label: 'Quote', type: 'text' },
    { key: 'partner-hero-image', label: 'Hero Image', type: 'image' },
    { key: 'partner-hero-title', label: 'Hero Title', type: 'text' },
    { key: 'partner-tier-1-title', label: 'Tier 1 Title', type: 'text' },
    { key: 'partner-tier-1-desc', label: 'Tier 1 Description', type: 'text' },
    { key: 'partner-tier-2-title', label: 'Tier 2 Title', type: 'text' },
    { key: 'partner-tier-2-desc', label: 'Tier 2 Description', type: 'text' },
    { key: 'partner-tier-3-title', label: 'Tier 3 Title', type: 'text' },
    { key: 'partner-tier-3-desc', label: 'Tier 3 Description', type: 'text' },
    { key: 'partner-cta-title', label: 'CTA Title', type: 'text' },
    { key: 'partner-cta-desc', label: 'CTA Description', type: 'text' },
    { key: 'partner-cta-btn', label: 'CTA Button', type: 'text' },
  ],
  'Contact Page': [
    { key: 'contact-section-label', label: 'Section Label', type: 'text' },
    { key: 'contact-title', label: 'Title', type: 'text' },
    { key: 'contact-title-accent', label: 'Accent Word', type: 'text' },
    { key: 'contact-desc', label: 'Description', type: 'text' },
    { key: 'contact-group-1-title', label: 'Group 1 Title', type: 'text' },
    { key: 'contact-group-1-label', label: 'Group 1 Label', type: 'text' },
    { key: 'contact-group-1-value', label: 'Group 1 Value', type: 'text' },
    { key: 'contact-group-2-title', label: 'Group 2 Title', type: 'text' },
    { key: 'contact-group-2-label', label: 'Group 2 Label', type: 'text' },
    { key: 'contact-group-2-value', label: 'Group 2 Value', type: 'text' },
    { key: 'contact-form-title', label: 'Form Title', type: 'text' },
    { key: 'contact-form-desc', label: 'Form Description', type: 'text' },
    { key: 'contact-btn-text', label: 'Button Text', type: 'text' },
  ],
  'Footer': [
    { key: 'footer-title-line1', label: 'Title Line 1', type: 'text' },
    { key: 'footer-title-accent', label: 'Title Accent', type: 'text' },
    { key: 'footer-title-line2', label: 'Title Line 2', type: 'text' },
    { key: 'footer-quote', label: 'Quote', type: 'text' },
    { key: 'footer-quote-author', label: 'Quote Author', type: 'text' },
    { key: 'footer-btn-invest', label: 'Invest Button', type: 'text' },
    { key: 'footer-btn-partner', label: 'Partner Button', type: 'text' },
    { key: 'footer-form-title', label: 'Form Title', type: 'text' },
    { key: 'footer-form-btn', label: 'Form Button', type: 'text' },
    { key: 'footer-nav-title', label: 'Nav Title', type: 'text' },
    { key: 'footer-nav-vision', label: 'Nav Vision', type: 'text' },
    { key: 'footer-nav-reports', label: 'Nav Reports', type: 'text' },
    { key: 'footer-nav-academy', label: 'Nav Academy', type: 'text' },
    { key: 'footer-nav-faq', label: 'Nav FAQ', type: 'text' },
    { key: 'footer-nav-contact', label: 'Nav Contact', type: 'text' },
    { key: 'footer-connect-title', label: 'Connect Title', type: 'text' },
    { key: 'footer-copyright', label: 'Copyright', type: 'text' },
    { key: 'footer-email', label: 'Email', type: 'text' },
    { key: 'footer-brand', label: 'Brand Name', type: 'text' },
  ],
  'Gallery': [
    { key: 'gallery-subtitle', label: 'Section Subtitle', type: 'text' },
    { key: 'gallery-title', label: 'Section Title', type: 'text' },
    { key: 'gallery-description', label: 'Description', type: 'text' },
  ],
  'Social Feed': [
    { key: 'social-section-label', label: 'Section Label', type: 'text' },
    { key: 'social-section-title', label: 'Section Title', type: 'text' },
    { key: 'social-section-desc', label: 'Description', type: 'text' },
  ],
};
